### ISSUE TITLE
check whether serverConfig.agent exists

### ISSUE THREAD

**Issue by mykiimike** [binarysec/gate#53]
```
* HTTP plugin failed TypeError: Cannot read property 'http' of undefined
    at Function.agent.loader (/usr/lib/node_modules/gatejs/src/lib/http/js/agent.js:50:54)
    at Function.http.loader (/usr/lib/node_modules/gatejs/src/lib/http/index.js:264:14)
    at new gatejs (/usr/lib/node_modules/gatejs/src/service.js:260:17)
    at Object.<anonymous> (/usr/lib/node_modules/gatejs/src/service.js:378:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

**Comment by pvlvsk** [comment]
Hello, how to solve this error? I have it too.

**Comment by mykiimike** [comment]
Can you clone the project then npm install -g in order to test my last commit ?

Thanks
Michael

**Comment by pvlvsk** [comment]
i cloned your project again, now i get another error:

`module.js:487
    throw err;
    ^

Error: Cannot find module 'node-ipaddr'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at new gatejs (/home/andrej/gate/src/service.js:212:20)
    at Object.<anonymous> (/home/andrej/gate/src/service.js:378:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)`

**Comment by pvlvsk** [comment]
Sorry, had to install with --unsafe-perm. Now its working!

**Comment by mykiimike** [comment]
Cool i do the release on npm! 

Thanks for the report

All the best
Michael
