### ISSUE TITLE
diskusage@0.2.6 dependency failed to install on nodejs 12

### ISSUE THREAD

**Issue by kokizzu** [binarysec/gate#62]
time to upgrade to [diskusage@1.1.3](https://www.npmjs.com/package/diskusage)?
```
/usr/bin/gatejs -> /usr/lib/node_modules/gatejs/src/service.js

> diskusage@0.2.6 install /usr/lib/node_modules/gatejs/node_modules/diskusage
> node-gyp rebuild

make: Entering directory '/usr/lib/node_modules/gatejs/node_modules/diskusage/build'
  CXX(target) Release/obj.target/diskusage/src/main.o
../src/main.cpp: In function ‘v8::Local<v8::Object> ConvertDiskUsage(const DiskUsage&)’:
../src/main.cpp:9:124: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     obj->Set(Nan::New<v8::String>("available").ToLocalChecked(), Nan::New<v8::Number>(static_cast<double>(usage.available)));
                                                                                                                            ^
In file included from /home/asd/.cache/node-gyp/12.16.1/include/node/v8-internal.h:14:0,
                 from /home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:27,
                 from /home/asd/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/main.cpp:3:
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:3499:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^
/home/asd/.cache/node-gyp/12.16.1/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/main.cpp:10:114: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     obj->Set(Nan::New<v8::String>("free").ToLocalChecked(), Nan::New<v8::Number>(static_cast<double>(usage.free)));
                                                                                                                  ^
In file included from /home/asd/.cache/node-gyp/12.16.1/include/node/v8-internal.h:14:0,
                 from /home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:27,
                 from /home/asd/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/main.cpp:3:
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:3499:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^
/home/asd/.cache/node-gyp/12.16.1/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/main.cpp:11:116: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     obj->Set(Nan::New<v8::String>("total").ToLocalChecked(), Nan::New<v8::Number>(static_cast<double>(usage.total)));
                                                                                                                    ^
In file included from /home/asd/.cache/node-gyp/12.16.1/include/node/v8-internal.h:14:0,
                 from /home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:27,
                 from /home/asd/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/main.cpp:3:
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:3499:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^
/home/asd/.cache/node-gyp/12.16.1/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/main.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE GetDiskUsage(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/main.cpp:26:71: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’
         DiskUsage result = GetDiskUsage(*v8::String::Utf8Value(info[0]));
                                                                       ^
In file included from /home/asd/.cache/node-gyp/12.16.1/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/main.cpp:3:
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:3135:5: note: candidate: v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)
     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
     ^~~~~~~~~
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:3135:5: note:   candidate expects 2 arguments, 1 provided
../src/main.cpp: At global scope:
../src/main.cpp:37:15: error: variable or field ‘Init’ declared void
 void Init(v8::Handle<v8::Object> exports)
               ^~~~~~
../src/main.cpp:37:15: error: ‘Handle’ is not a member of ‘v8’
../src/main.cpp:37:32: error: expected primary-expression before ‘>’ token
 void Init(v8::Handle<v8::Object> exports)
                                ^
../src/main.cpp:37:34: error: ‘exports’ was not declared in this scope
 void Init(v8::Handle<v8::Object> exports)
                                  ^~~~~~~
In file included from ../../nan/nan.h:54:0,
                 from ../src/main.cpp:3:
../src/main.cpp:42:24: error: ‘Init’ was not declared in this scope
 NODE_MODULE(diskusage, Init)
                        ^
/home/asd/.cache/node-gyp/12.16.1/include/node/node.h:601:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../src/main.cpp:42:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(diskusage, Init)
 ^~~~~~~~~~~
../src/main.cpp:42:24: note: suggested alternative:
 NODE_MODULE(diskusage, Init)
                        ^
/home/asd/.cache/node-gyp/12.16.1/include/node/node.h:601:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../src/main.cpp:42:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(diskusage, Init)
 ^~~~~~~~~~~
/home/asd/.cache/node-gyp/12.16.1/include/node/node.h:217:18: note:   ‘node::Init’
 NODE_EXTERN void Init(int* argc,
                  ^~~~
In file included from ../src/main.cpp:3:0:
../src/main.cpp:21:19: warning: ‘Nan::NAN_METHOD_RETURN_TYPE GetDiskUsage(Nan::NAN_METHOD_ARGS_TYPE)’ defined but not used [-Wunused-function]
 static NAN_METHOD(GetDiskUsage)
                   ^
../../nan/nan.h:1566:33: note: in definition of macro ‘NAN_METHOD’
     Nan::NAN_METHOD_RETURN_TYPE name(Nan::NAN_METHOD_ARGS_TYPE info)
                                 ^~~~
diskusage.target.mk:114: recipe for target 'Release/obj.target/diskusage/src/main.o' failed
make: *** [Release/obj.target/diskusage/src/main.o] Error 1
make: Leaving directory '/usr/lib/node_modules/gatejs/node_modules/diskusage/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-76-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/gatejs/node_modules/diskusage
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! diskusage@0.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the diskusage@0.2.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by kokizzu** [comment]
Ah, even with latest diskusage 1.1.3 it also have errors:

```
> gatejs@2.0.14 postinstall /home/asd/MEGA/go/src/gatejs
> make

cd ./src/lib/core && node-gyp rebuild
make[1]: Entering directory '/home/asd/MEGA/go/src/gatejs/src/lib/core/build'
  CXX(target) Release/obj.target/core/src/utils.o
In file included from ../src/utils.cc:22:0:
../src/utils.hh:28:24: error: ‘v8::Handle’ has not been declared
   static void Init(v8::Handle<v8::Object> exports);
                        ^~~~~~
../src/utils.hh:28:30: error: expected ‘,’ or ‘...’ before ‘<’ token
   static void Init(v8::Handle<v8::Object> exports);
                              ^
../src/utils.cc:30:22: error: variable or field ‘Init’ declared void
 void CoreUtils::Init(Handle<Object> exports) {
                      ^~~~~~
../src/utils.cc:30:22: error: ‘Handle’ was not declared in this scope
../src/utils.cc:30:22: note: suggested alternative: ‘rand_r’
 void CoreUtils::Init(Handle<Object> exports) {
                      ^~~~~~
                      rand_r
../src/utils.cc:30:35: error: expected primary-expression before ‘>’ token
 void CoreUtils::Init(Handle<Object> exports) {
                                   ^
../src/utils.cc:30:37: error: ‘exports’ was not declared in this scope
 void CoreUtils::Init(Handle<Object> exports) {
                                     ^~~~~~~
../src/utils.cc: In static member function ‘static void CoreUtils::dateToStr(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/utils.cc:54:45: error: no matching function for call to ‘v8::Value::ToString()’
     String::Utf8Value tmp(args[0]->ToString());
                                             ^
In file included from /home/asd/.cache/node-gyp/12.16.1/include/node/node.h:63:0,
                 from ../src/utils.cc:21:
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:2668:44: note: candidate: v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                            ^~~~~~~~
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:2668:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/asd/.cache/node-gyp/12.16.1/include/node/v8-internal.h:14:0,
                 from /home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:27,
                 from /home/asd/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../src/utils.cc:21:
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:2684:31: note: candidate: v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/home/asd/.cache/node-gyp/12.16.1/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:2684:31: note:   candidate expects 1 argument, 0 provided
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/home/asd/.cache/node-gyp/12.16.1/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/utils.cc:61:45: error: no matching function for call to ‘v8::Value::ToString()’
     String::Utf8Value tmp(args[1]->ToString());
                                             ^
In file included from /home/asd/.cache/node-gyp/12.16.1/include/node/node.h:63:0,
                 from ../src/utils.cc:21:
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:2668:44: note: candidate: v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                            ^~~~~~~~
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:2668:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/asd/.cache/node-gyp/12.16.1/include/node/v8-internal.h:14:0,
                 from /home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:27,
                 from /home/asd/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../src/utils.cc:21:
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:2684:31: note: candidate: v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/home/asd/.cache/node-gyp/12.16.1/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:2684:31: note:   candidate expects 1 argument, 0 provided
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/home/asd/.cache/node-gyp/12.16.1/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/utils.cc:75:64: warning: ‘static v8::Local<v8::String> v8::String::NewFromUtf8(v8::Isolate*, const char*, v8::String::NewStringType, int)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   args.GetReturnValue().Set(String::NewFromUtf8(isolate, buffer));
                                                                ^
In file included from /home/asd/.cache/node-gyp/12.16.1/include/node/v8-internal.h:14:0,
                 from /home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:27,
                 from /home/asd/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../src/utils.cc:21:
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:3032:21: note: declared here
       Local<String> NewFromUtf8(Isolate* isolate, const char* data,
                     ^
/home/asd/.cache/node-gyp/12.16.1/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/utils.cc: In static member function ‘static void CoreUtils::cstrrev(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/utils.cc:86:28: error: no matching function for call to ‘v8::Value::ToString()’
  input = args[0]->ToString();
                            ^
In file included from /home/asd/.cache/node-gyp/12.16.1/include/node/node.h:63:0,
                 from ../src/utils.cc:21:
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:2668:44: note: candidate: v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                            ^~~~~~~~
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:2668:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/asd/.cache/node-gyp/12.16.1/include/node/v8-internal.h:14:0,
                 from /home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:27,
                 from /home/asd/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../src/utils.cc:21:
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:2684:31: note: candidate: v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/home/asd/.cache/node-gyp/12.16.1/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:2684:31: note:   candidate expects 1 argument, 0 provided
                 Local<String> ToString(Isolate* isolate) const);
                               ^
/home/asd/.cache/node-gyp/12.16.1/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/utils.cc:87:29: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::String>&)’
  String::Utf8Value tmp(input);
                             ^
In file included from /home/asd/.cache/node-gyp/12.16.1/include/node/node.h:63:0,
                 from ../src/utils.cc:21:
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:3135:5: note: candidate: v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)
     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
     ^~~~~~~~~
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:3135:5: note:   candidate expects 2 arguments, 1 provided
../src/utils.cc:90:60: warning: ‘static v8::Local<v8::String> v8::String::NewFromUtf8(v8::Isolate*, const char*, v8::String::NewStringType, int)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   args.GetReturnValue().Set(String::NewFromUtf8(isolate, ""));
                                                            ^
In file included from /home/asd/.cache/node-gyp/12.16.1/include/node/v8-internal.h:14:0,
                 from /home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:27,
                 from /home/asd/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../src/utils.cc:21:
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:3032:21: note: declared here
       Local<String> NewFromUtf8(Isolate* isolate, const char* data,
                     ^
/home/asd/.cache/node-gyp/12.16.1/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/utils.cc:100:45: warning: ‘static v8::Local<v8::String> v8::String::NewFromUtf8(v8::Isolate*, const char*, v8::String::NewStringType, int)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
  input = String::NewFromUtf8(isolate, buffer);
                                             ^
In file included from /home/asd/.cache/node-gyp/12.16.1/include/node/v8-internal.h:14:0,
                 from /home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:27,
                 from /home/asd/.cache/node-gyp/12.16.1/include/node/node.h:63,
                 from ../src/utils.cc:21:
/home/asd/.cache/node-gyp/12.16.1/include/node/v8.h:3032:21: note: declared here
       Local<String> NewFromUtf8(Isolate* isolate, const char* data,
                     ^
/home/asd/.cache/node-gyp/12.16.1/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
core.target.mk:113: recipe for target 'Release/obj.target/core/src/utils.o' failed
make[1]: *** [Release/obj.target/core/src/utils.o] Error 1
make[1]: Leaving directory '/home/asd/MEGA/go/src/gatejs/src/lib/core/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-76-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/asd/MEGA/go/src/gatejs/src/lib/core
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok 
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! gatejs@2.0.14 postinstall: `make`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the gatejs@2.0.14 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
